#!/bin/bash


NPM_CONFIG=/data/config/server-config.json

NPMLAZY_HTTPS_ENABLED=${NPMLAZY_HTTPS_ENABLED:-false}
NPMLAZY_HTTPS_KEY=${NPMLAZY_HTTPS_KEY:-}
NPMLAZY_HTTPS_CERT=${NPMLAZY_HTTPS_CERT:-}

HTTP_PROXY=${HTTP_PROXY:-$http_proxy}
HTTPS_PROXY=${HTTPS_PROXY:-$https_proxy}
HTTP_PROXY=${HTTP_PROXY:-}
HTTPS_PROXY=${HTTPS_PROXY:-}

NPMLAZY_PUBLIC_PORT=${NPMLAZY_PUBLIC_PORT:-\"\"}
NPMLAZY_PUBLIC_HOST=${NPMLAZY_PUBLIC_HOST:-}

NPMLAZY_LOG=${NPMLAZXY_LOG:-info}

NPMLAZY_OFFLINE=${NPMLAZY_OFFLINE:-true}

NPMLAZY_UPSTREAM_HOST=${NPMLAZY_UPSTREAM_HOST:-registry.npmjs.org}
NPMLAZY_UPSTREAM_PORT=${NPMLAZY_UPSTREAM_PORT:-443}
NPMLAZY_UPSTREAM_USE_HTTPS=${NPMLAZY_UPSTREAM_USE_HTTPS:-true}
NPMLAZY_UPSTREAM_VERIFY_SSL=${NPMLAZY_UPSTREAM_VERIFY_SSL:-true}
NPMLAZY_UPSTREAM_DBPATH=${NPMLAZY_UPSTREAM_DBPATH:-/}

NPMLAZY_CACHE_EXPIRY=${NPMLAZY_CACHE_EXPIRY:-320000}
NPMLAZY_CACHE_INMEM=${NMLAZY_CACHE_INMEM:-200}

set


# apply config
sed -i "s|{{NPMLAZY_HTTPS_ENABLED}}|$NPMLAZY_HTTPS_ENABLED|g" $NPM_CONFIG
sed -i "s|{{NPMLAZY_HTTPS_KEY}}|$NPMLAZY_HTTPS_KEY|g" $NPM_CONFIG
sed -i "s|{{NPMLAZY_HTTPS_CERT}}|$NPMLAZY_HTTPS_CERT|g" $NPM_CONFIG
sed -i "s|{{HTTP_PROXY}}|$HTTP_PROXY|g" $NPM_CONFIG
sed -i "s|{{HTTPS_PROXY}}|$HTTPS_PROXY|g" $NPM_CONFIG
sed -i "s|{{NPMLAZY_PUBLIC_PORT}}|$NPMLAZY_PUBLIC_PORT|g" $NPM_CONFIG
sed -i "s|{{NPMLAZY_PUBLIC_HOST}}|$NPMLAZY_PUBLIC_HOST|g" $NPM_CONFIG
sed -i "s|{{NPMLAZY_LOG}}|$NPMLAZY_LOG|g" $NPM_CONFIG
sed -i "s|{{NPMLAZY_OFFLINE}}|$NPMLAZY_OFFLINE|g" $NPM_CONFIG
sed -i "s|{{NPMLAZY_UPSTREAM_HOST}}|$NPMLAZY_UPSTREAM_HOST|g" $NPM_CONFIG
sed -i "s|{{NPMLAZY_UPSTREAM_PORT}}|$NPMLAZY_UPSTREAM_PORT|g" $NPM_CONFIG
sed -i "s|{{NPMLAZY_UPSTREAM_USE_HTTPS}}|$NPMLAZY_UPSTREAM_USE_HTTPS|g" $NPM_CONFIG
sed -i "s|{{NPMLAZY_UPSTREAM_VERIFY_SSL}}|$NPMLAZY_UPSTREAM_VERIFY_SSL|g" $NPM_CONFIG
sed -i "s|{{NPMLAZY_UPSTREAM_DBPATH}}|$NPMLAZY_UPSTREAM_DBPATH|g" $NPM_CONFIG
sed -i "s|{{NPMLAZY_CACHE_EXPIRY}}|$NPMLAZY_CACHE_EXPIRY|g" $NPM_CONFIG
sed -i "s|{{NPMLAZY_CACHE_INMEM}}|$NPMLAZY_CACHE_INMEM|g" $NPM_CONFIG

# run
npm-lazy-mirror -C $NPM_CONFIG
